"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

type Streamer = { id: string; name: string; handle: string; kick: string; logo: string; verified: boolean; slug: string };
type Status = { slug: string; isLive: boolean; title: string; viewers: number; thumbnail: string; startedAt: string | null };
type Metric = { id: string; slug: string; date: string; maxViewers: number; liveMinutes: number; streamCount: number; lastLiveAt: string | null };

export function AdminMediaCenter({ streamers, statuses, metrics }: { streamers: Streamer[]; statuses: Status[]; metrics: Metric[] }) {
  const router = useRouter(); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const sync = async () => { setLoading(true); setError(""); try { const response=await fetch("/api/admin/media/sync",{method:"POST"}); const result=await response.json().catch(()=>null); if(!response.ok) throw new Error(result?.error??"فشل التحديث"); router.refresh(); } catch(cause){setError(cause instanceof Error?cause.message:"تعذر الاتصال");} finally{setLoading(false);} };
  const statusMap=new Map(statuses.map((item)=>[item.slug,item]));
  const rows=streamers.map((streamer)=>{const history=metrics.filter((item)=>item.slug===streamer.slug); return {streamer,status:statusMap.get(streamer.slug),max:Math.max(0,...history.map((item)=>item.maxViewers)),minutes:history.reduce((sum,item)=>sum+item.liveMinutes,0),streams:history.reduce((sum,item)=>sum+item.streamCount,0)};}).sort((a,b)=>(b.status?.viewers??0)-(a.status?.viewers??0)||b.max-a.max);
  const live=rows.filter((row)=>row.status?.isLive);
  return <><header className="tokyo-glass rounded-[34px] p-6 md:p-9"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black tracking-[5px] text-[#53fc18]">TOKYO MEDIA INTELLIGENCE</p><h1 className="tokyo-section-title mt-3 text-4xl font-black md:text-6xl">مركز الستريمرز</h1><p className="mt-4 max-w-3xl leading-8 text-zinc-400">حالة البث الحية، أعلى مشاهدة، الوقت المسجل وترتيب صناع المحتوى.</p></div><button disabled={loading} onClick={sync} className="rounded-2xl bg-[#53fc18] px-7 py-4 font-black text-black disabled:opacity-50">{loading?"جاري الاتصال بـ Kick...":"تحديث الإحصائيات"}</button></div><div className="mt-7 grid gap-3 md:grid-cols-4">{[["الستريمرز",rows.length],["مباشر الآن",live.length],["المشاهدون الآن",live.reduce((s,r)=>s+(r.status?.viewers??0),0)],["ساعات مسجلة",Math.round(rows.reduce((s,r)=>s+r.minutes,0)/60)]].map(([l,v])=><div key={l} className="rounded-2xl border border-white/10 bg-black/40 p-4"><p className="text-xs text-zinc-500">{l}</p><p className="mt-2 text-3xl font-black">{v}</p></div>)}</div></header>{error&&<p className="mt-5 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-red-200">{error}</p>}<section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((row,index)=><article key={row.streamer.id} className={`tokyo-panel p-5 ${row.status?.isLive?"border-[#53fc18]/35 shadow-[0_0_38px_rgba(83,252,24,0.08)]":""}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black tracking-[3px] text-zinc-600">RANK #{index+1}</p><h2 className="mt-2 text-2xl font-black">{row.streamer.name}</h2><p className="mt-1 text-sm text-zinc-500">{row.streamer.handle}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${row.status?.isLive?"bg-[#53fc18] text-black":"bg-white/5 text-zinc-500"}`}>{row.status?.isLive?"LIVE":"OFFLINE"}</span></div>{row.status?.isLive&&<div className="mt-4 rounded-2xl border border-[#53fc18]/20 bg-[#53fc18]/5 p-4"><p className="line-clamp-2 font-black text-[#b9ffa1]">{row.status.title}</p><p className="mt-2 text-2xl font-black">{row.status.viewers} مشاهد</p></div>}<div className="mt-4 grid grid-cols-3 gap-2">{[["أعلى مشاهدة",row.max],["ساعات",Math.round(row.minutes/60)],["بثوث",row.streams]].map(([l,v])=><div key={l} className="rounded-xl border border-white/10 bg-black/35 p-3 text-center"><p className="text-[10px] text-zinc-600">{l}</p><p className="mt-1 font-black">{v}</p></div>)}</div><a href={row.streamer.kick} target="_blank" rel="noreferrer" className="mt-4 flex justify-center rounded-xl border border-[#53fc18]/20 px-4 py-3 font-black text-[#53fc18]">فتح قناة Kick</a></article>)}</section></>;
}
