"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

type Member = { id: string; displayName: string; username: string; internalRank: string; commandPoints: number; activityScore: number };
type Assignment = { id: string; status: string; evidence: string | null; adminNote: string | null; completedAt: string | null; member: Pick<Member, "id" | "displayName" | "username"> };
type Task = { id: string; title: string; description: string; category: string; points: number; status: string; dueAt: string | null; assignments: Assignment[] };

export function AdminProgressionCenter({ members, tasks, season, achievements }: { members: Member[]; tasks: Task[]; season: { name: string; startsAt: string; endsAt: string } | null; achievements: Array<{ id: string; title: string; description: string; icon: string; points: number; _count: { members: number } }> }) {
  const router = useRouter();
  const [createOpen, setCreateOpen] = useState(false);
  const [seasonOpen, setSeasonOpen] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [loading, setLoading] = useState("");
  const [error, setError] = useState("");

  const post = async (payload: Record<string, unknown>) => {
    setLoading("POST"); setError("");
    try { const response = await fetch("/api/admin/progression", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.error ?? "فشل الحفظ"); setCreateOpen(false); setSeasonOpen(false); setSelected([]); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر الاتصال"); } finally { setLoading(""); }
  };
  const updateAssignment = async (taskId: string, assignmentId: string, status: string) => {
    const note = status === "FAILED" ? prompt("سبب عدم الإنجاز")?.trim() : undefined;
    setLoading(assignmentId); setError("");
    try { const response = await fetch(`/api/admin/progression/assignments/${assignmentId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, adminNote: note }) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.error ?? "فشل التحديث"); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر الاتصال"); } finally { setLoading(""); }
  };

  return <>
    <header className="tokyo-glass rounded-[34px] p-6 md:p-9"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black tracking-[5px] text-yellow-300">TOKYO PROGRESSION</p><h1 className="tokyo-section-title mt-3 text-4xl font-black md:text-6xl">المهام والترقيات</h1><p className="mt-4 max-w-3xl leading-8 text-zinc-400">تكليفات فعلية، نقاط قيادة، أوسمة وموسم تنافسي داخل العصابة.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setSeasonOpen(true)} className="rounded-2xl border border-cyan-400/25 bg-cyan-400/10 px-5 py-3 font-black text-cyan-200">إدارة الموسم</button><button onClick={() => setCreateOpen(true)} className="rounded-2xl bg-yellow-300 px-6 py-3 font-black text-black">+ مهمة جديدة</button></div></div>
      <div className="mt-7 grid gap-3 md:grid-cols-4">{[["الموسم", season?.name ?? "بدون موسم"],["مهام نشطة", tasks.filter((task) => task.status === "ACTIVE").length],["إنجازات مكتملة", tasks.flatMap((task) => task.assignments).filter((item) => item.status === "COMPLETED").length],["مجموع النقاط", members.reduce((sum, member) => sum + member.commandPoints, 0)]].map(([label,value]) => <div key={label} className="rounded-2xl border border-white/10 bg-black/40 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>
    </header>
    {error && <p className="sticky top-3 z-50 mt-5 rounded-2xl border border-red-400/25 bg-red-950/95 p-4 font-black text-red-200">{error}</p>}
    <section className="my-6 grid gap-5 lg:grid-cols-[0.72fr_1.28fr]"><div className="grid content-start gap-5"><div className="tokyo-panel p-5"><p className="text-xs font-black tracking-[4px] text-cyan-300">LEADERBOARD</p><div className="mt-4 grid gap-2">{members.slice(0, 12).map((member,index) => <div key={member.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/35 p-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl font-black ${index < 3 ? "bg-yellow-300 text-black" : "bg-white/5 text-zinc-500"}`}>{index+1}</span><span className="min-w-0 flex-1"><strong className="block truncate">{member.displayName}</strong><small className="text-zinc-600">{member.internalRank} — نشاط {member.activityScore}</small></span><strong className="text-yellow-300">{member.commandPoints} XP</strong></div>)}</div></div><div className="tokyo-panel p-5"><p className="text-xs font-black tracking-[4px] text-fuchsia-300">ACHIEVEMENTS</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-1">{achievements.map((achievement) => <div key={achievement.id} className="rounded-2xl border border-white/10 bg-black/35 p-4"><div className="flex items-center gap-3"><span className="text-3xl text-yellow-300">{achievement.icon}</span><div><strong>{achievement.title}</strong><p className="mt-1 text-xs text-zinc-500">{achievement.description}</p></div></div><p className="mt-3 text-xs font-black text-cyan-300">{achievement._count.members} حاصلين عليه</p></div>)}</div></div></div>
      <div className="grid content-start gap-4">{tasks.length === 0 && <div className="rounded-3xl border border-dashed border-white/15 p-12 text-center text-zinc-500">لا توجد مهام بعد.</div>}{tasks.map((task) => <article key={task.id} className="tokyo-panel p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2"><span className="rounded-full border border-yellow-400/20 bg-yellow-400/10 px-3 py-1 text-xs font-black text-yellow-200">{task.category}</span><span className="rounded-full border border-cyan-400/20 px-3 py-1 text-xs font-black text-cyan-200">+{task.points} XP</span></div><h2 className="mt-3 text-2xl font-black">{task.title}</h2><p className="mt-2 leading-7 text-zinc-400">{task.description}</p></div>{task.dueAt && <span className="text-xs text-zinc-500">حتى {new Date(task.dueAt).toLocaleString("ar")}</span>}</div><div className="mt-5 grid gap-2">{task.assignments.map((assignment) => <div key={assignment.id} className="grid gap-2 rounded-2xl border border-white/10 bg-black/40 p-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><strong>{assignment.member.displayName}</strong><p className="mt-1 text-xs text-zinc-600">@{assignment.member.username} — {assignment.status}</p></div><select value={assignment.status} disabled={loading === assignment.id} onChange={(event) => void updateAssignment(task.id, assignment.id, event.target.value)} className={`rounded-xl border px-3 py-2 text-xs font-black ${assignment.status === "COMPLETED" ? "border-green-400/25 bg-green-400/10 text-green-300" : assignment.status === "FAILED" ? "border-red-400/25 bg-red-400/10 text-red-300" : "border-white/10 bg-zinc-950"}`}><option value="ASSIGNED">مكلّف</option><option value="IN_PROGRESS">قيد التنفيذ</option><option value="COMPLETED">مكتملة</option><option value="FAILED">لم تنجز</option></select></div>)}</div></article>)}</div></section>
    {createOpen && <Modal title="إنشاء مهمة" close={() => setCreateOpen(false)}><form action={(data) => void post({ title:data.get("title"), description:data.get("description"), category:data.get("category"), points:Number(data.get("points")), dueAt:data.get("dueAt") ? new Date(String(data.get("dueAt"))).toISOString() : undefined, memberIds:selected })} className="grid gap-4"><input name="title" required placeholder="عنوان المهمة" className="input"/><textarea name="description" required placeholder="تفاصيل المهمة" className="input min-h-24"/><div className="grid grid-cols-2 gap-3"><select name="category" className="input"><option value="OPERATIONS">عمليات</option><option value="SECURITY">أمن</option><option value="ACTIVITY">نشاط</option><option value="MEDIA">إعلام</option><option value="GENERAL">عام</option></select><input name="points" type="number" min="1" max="500" defaultValue="25" className="input"/></div><input name="dueAt" type="datetime-local" className="input"/><div className="tokyo-scrollbar grid max-h-52 gap-2 overflow-y-auto sm:grid-cols-2">{members.map((member) => <label key={member.id} className={`flex cursor-pointer gap-2 rounded-xl border p-3 ${selected.includes(member.id) ? "border-yellow-300/40 bg-yellow-300/10" : "border-white/10"}`}><input type="checkbox" checked={selected.includes(member.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current,member.id] : current.filter((id) => id !== member.id))}/>{member.displayName}</label>)}</div><button disabled={Boolean(loading)} className="rounded-2xl bg-yellow-300 py-4 font-black text-black">إنشاء وإرسال التكليف</button></form></Modal>}
    {seasonOpen && <Modal title="بدء موسم جديد" close={() => setSeasonOpen(false)}><form action={(data) => void post({ action:"SEASON", seasonName:data.get("name"), startsAt:new Date(String(data.get("startsAt"))).toISOString(), endsAt:new Date(String(data.get("endsAt"))).toISOString() })} className="grid gap-4"><input name="name" required placeholder="اسم الموسم" className="input"/><input name="startsAt" type="datetime-local" required className="input"/><input name="endsAt" type="datetime-local" required className="input"/><button className="rounded-2xl bg-cyan-300 py-4 font-black text-black">بدء الموسم</button></form></Modal>}
  </>;
}

function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[220] overflow-y-auto bg-black/90 p-4 backdrop-blur-xl"><div className="mx-auto mt-10 max-w-2xl rounded-[28px] border border-white/15 bg-zinc-950 p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} className="rounded-xl border border-white/15 px-4 py-2">إغلاق</button></div>{children}</div></div>; }
